version: "3.9"

services:
  backend:
    build: .
    container_name: libraai-backend

    ports:
      - "5000:5000"

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - libraai-network

networks:
  libraai-network:
    driver: bridge