export const NOTIFICATION_TYPES = {

    BOOK_DUE: "BOOK_DUE",

    FINE_GENERATED: "FINE_GENERATED",

    RESERVATION_CREATED: "RESERVATION_CREATED",

    RESERVATION_EXPIRED: "RESERVATION_EXPIRED",

    BOOK_AVAILABLE: "BOOK_AVAILABLE",

    BOOK_ISSUED: "BOOK_ISSUED"

};